### PR TITLE
Use ST_ClipByBox2D along ST_AsTWKB

### PR DESCRIPTION
**Pull request by rochoa**

### CODE REVIEW

**Comment by rochoa** [comment]
What do you think @pramsey ?

**Comment by rochoa** [comment]
cc @zenitraM

**Comment by pramsey** [comment]
I'm OK w/ code change, if you think you have reasonable numbers to plug in to the controls for the clipper. I feel like the right answer for "clipper for performance reasons" is a slightly custom clipper that looks at (a) the ratio of intersection of the object box and the clipping box (looking for low ration) and (b) the object size in order to determine clip-worthiness.

**Comment by rochoa** [comment]
Hehe, I agree with you we could make it better by applying those rules but not sure how easy are to apply at that level without making the ratio intersection / object size calculation the most expensive part of the query.

**Comment by pramsey** [comment]
I admit, I was thinking about a custom C function that would have cheap access to the bounding boxes and the VARSIZE of the object.

**Comment by rochoa** [comment]
Let's consider that for a future improvement, deal?

**Comment by pramsey** [comment]
Sold

**Comment by zenitraM** [comment]
:flags:

**Pull request merged**
